# Generated by Django 3.2.4 on 2021-09-09 21:38

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyContentType',
            fields=[
            ],
            options={
                'managed': False,
                'proxy': True,
            },
            bases=('contenttypes.contenttype',),
        ),
    ]
